### ISSUE TITLE
Замечания по коду

### ISSUE THREAD

**Issue by MeGaPk** [blinchk/tthk-replacements-bot#18]
1) используй prepare statements при запросах: https://pymysql.readthedocs.io/en/latest/user/examples.html
тогда проблем с инъекциями не будет...
2) код раскидай по классам и по файлам. 
3) много повторяющихся строк по типу "event.text.lower()" можно легко в pycharm'e вынести в одну переменную
4) плохой тон в репозиторий закидывать папки .vs / .idea
5) Советую поизучать тему SOLID, вот прикольный канал https://www.youtube.com/c/ExtremeCode/playlists (ЯП без разницы)

**Comment by blinchk** [comment]
@MeGaPk,
1. Библиотека PyMySQL делает это очень больно и трудно, **CodeFactor** в данный момент не видит в них ошибок безопасности, да и в целом инъекции наврятли возможны из-за выборки вводимых значений в %s.
2. Использование большинства файлов на данный момент трудно реализуемо на той площадке, где щас расположен бот. Да и после одной попытки полной реконструкции кода, ничего работать лучше не стало. Поэтому не вижу смысла щас всё переписывать.
3. В переменную вынес в последних коммитах.
4. Тут не спорю, папки удалил.
5. В коде некоторые абстракции расположены на совершенно разных уровнях, но реализация большинства принципов ООП на динамически-типизированном языке очень трудна. Поэтому данный проект либо будет переноситься на другую технологию, либо же будет поддерживаться в виде как есть. Ресурсы на его исправления по факту просто недостижимы.
